import { FileText, ArrowRight } from 'lucide-react';
import { PageId } from '../types';
import Reveal from './Reveal';

interface TermsViewProps {
  onNavigate: (pageId: PageId) => void;
}

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing the AiGROW website and using our services, calculators, or equipment shop, you agree to be bound by these Terms of Service. If you do not agree, please discontinue use of the site.'
  },
  {
    title: '2. Services & Estimates',
    body: 'Cost estimates generated by our price calculator are provisional and for planning purposes only. All figures exclude VAT and local logistics charges and are subject to a physical site audit and formal technical proposal before any commitment.'
  },
  {
    title: '3. Equipment Purchases',
    body: 'Adding items to the cart and submitting a checkout inquiry initiates an official pricing quotation request, not a binding sale. Final pricing, availability, delivery timelines, and warranty terms are confirmed in your formal quotation.'
  },
  {
    title: '4. Intellectual Property',
    body: 'All content on this site — including designs, text, logos, software, and system architecture — is the property of AiGROW and CodeGen International and may not be reproduced or redistributed without written permission.'
  },
  {
    title: '5. Warranties & Liability',
    body: 'Equipment is covered by the specific warranty stated in its quotation. AiGROW is not liable for indirect or consequential losses arising from misuse, unauthorized modification, or improper installation of supplied systems.'
  },
  {
    title: '6. Project Engagements',
    body: 'Design-build and consultation engagements are governed by a separate signed agreement that supersedes these general terms for the scope of that project, including payment milestones and deliverables.'
  },
  {
    title: '7. Governing Law',
    body: 'These Terms are governed by the laws of Sri Lanka. Any disputes shall be subject to the exclusive jurisdiction of the courts of Colombo.'
  }
];

export default function TermsView({ onNavigate }: TermsViewProps) {
  return (
    <div className="bg-[#FAFDFB]/10 min-h-screen py-12 px-6">
      <div className="w-full max-w-4xl mx-auto">

        {/* Header */}
        <Reveal className="text-center mb-14">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 text-emerald-800 text-xs font-semibold uppercase tracking-wider mb-4">
            <FileText className="w-3.5 h-3.5" />
            Legal & Compliance
          </div>
          <h1 className="font-sans text-4xl font-extrabold tracking-tight text-gray-950 mb-4">
            Terms of Service
          </h1>
          <p className="font-sans text-gray-500 font-light text-base md:text-lg">
            The terms governing your use of AiGROW's website and services.
          </p>
          <p className="font-mono text-[11px] text-gray-400 uppercase tracking-wider mt-4">
            Last updated: January 2026
          </p>
        </Reveal>

        {/* Sections */}
        <div className="flex flex-col gap-6">
          {SECTIONS.map((section, idx) => (
            <Reveal
              key={section.title}
              delay={Math.min(idx * 0.05, 0.3)}
              className="glass rounded-2xl p-6 md:p-8 shadow-sm"
            >
              <h2 className="font-sans text-lg font-bold text-gray-950 mb-3">
                {section.title}
              </h2>
              <p className="font-sans text-sm text-gray-600 leading-relaxed font-light">
                {section.body}
              </p>
            </Reveal>
          ))}
        </div>

        {/* Contact CTA */}
        <Reveal className="mt-10 bg-emerald-950 text-white rounded-3xl p-8 md:p-10 flex flex-col gap-4">
          <h3 className="font-sans text-xl font-bold">Need clarification?</h3>
          <p className="font-sans text-sm text-gray-300 font-light leading-relaxed max-w-xl">
            Our team is happy to explain any term before you commit to a project or purchase.
          </p>
          <button
            onClick={() => {
              onNavigate('contact');
              window.scrollTo({ top: 0, behavior: 'smooth' });
            }}
            className="w-fit mt-2 px-6 py-3 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl font-semibold text-sm transition-all flex items-center gap-2 group"
          >
            Contact Us
            <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
          </button>
        </Reveal>

      </div>
    </div>
  );
}
